export enum RewardsActionTypes {
  GET_REWARDS = 'rewards/GET_REWARDS',
  GET_REWARDS_SUCCESS = 'rewards/GET_REWARDS_SUCCESS',
  GET_REWARDS_FAIL = 'rewards/GET_REWARDS_FAIL',
  UPDATE_REWARD = 'rewards/UPDATE_REWARD',
  UPDATE_REWARD_SUCCESS = 'rewards/UPDATE_REWARD_SUCCESS',
  UPDATE_REWARD_FAIL = 'rewards/UPDATE_REWARD_FAIL'
}
